# Generated by Django 3.1.2 on 2021-11-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_proxima_NFE', models.CharField(blank=True, max_length=100, verbose_name='Numero Próxima NFE')),
                ('numero_proxima_NFS', models.CharField(blank=True, max_length=100, verbose_name='Numero Próxima NFS')),
                ('prensa', models.CharField(blank=True, max_length=100, verbose_name='Prensa')),
                ('remanufatura', models.CharField(blank=True, max_length=100, verbose_name='Remanufatura')),
                ('triagem', models.CharField(blank=True, max_length=100, verbose_name='Triagem')),
                ('unidade_de_medida', models.CharField(blank=True, max_length=6, verbose_name='Unidade de medida')),
            ],
            options={
                'verbose_name_plural': 'Parâmetros',
            },
        ),
    ]
