# Generated by Django 3.1.2 on 2021-09-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('lote', '0002_auto_20210915_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedores.fornecedores', verbose_name='Fornecedores'),
        ),
    ]
