# Generated by Django 3.1.2 on 2021-01-29 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('socios', '0001_initial'),
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteItens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('finalizado', models.DateTimeField(verbose_name='Finalizado')),
                ('iniciado', models.DateTimeField(verbose_name='Iniciado')),
                ('num_recipiente', models.IntegerField(verbose_name='Numero do Recipiente')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('tempo_total', models.IntegerField(verbose_name='Tempo Total')),
                ('num_lote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lote.lote', verbose_name='Lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.produtos', verbose_name='Produtos')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='socios.socios', verbose_name='Socios')),
            ],
            options={
                'verbose_name_plural': 'Itens do Lote',
            },
        ),
    ]
