# Generated by Django 3.1.2 on 2021-02-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteItens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteitens',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade'),
        ),
    ]
