# Generated by Django 3.1.2 on 2021-01-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CNPJ_CPF', models.CharField(max_length=18, unique=True, verbose_name='CNPJ ou CPF')),
                ('razao_social_nome', models.CharField(max_length=100, verbose_name='Razão social ou Nome')),
                ('IE', models.CharField(max_length=9, verbose_name='IE')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('CEP', models.CharField(max_length=9, verbose_name='CEP')),
                ('UF', models.CharField(max_length=2, verbose_name='UF')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
