# Generated by Django 3.1.2 on 2020-10-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedores',
            name='CNPJ_CPF',
            field=models.CharField(max_length=18, unique=True, verbose_name='CNPJ/CPF'),
        ),
    ]
