# Generated by Django 3.1.2 on 2021-01-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('qualidades', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de Compra')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de Venda')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='valores_fornecedor', to='fornecedores.fornecedores', verbose_name='Fornecedores')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='valores_produto', to='produtos.produtos', verbose_name='Produtos')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='valores_qualidade', to='qualidades.qualidades', verbose_name='Qualidades')),
            ],
            options={
                'verbose_name_plural': 'Valores',
            },
        ),
    ]
