# Generated by Django 3.1.2 on 2021-10-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
