# Generated by Django 3.1.2 on 2021-11-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor'),
        ),
    ]
