# Generated by Django 3.1.2 on 2021-01-29 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualidades', '0001_initial'),
        ('produtos', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.CharField(max_length=100, unique=True, verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fornecedor', to='fornecedores.fornecedores', verbose_name='Fornecedores')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto', to='produtos.produtos', verbose_name='Produtos')),
                ('qualidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qualidade', to='qualidades.qualidades', verbose_name='Qualidades')),
            ],
            options={
                'verbose_name_plural': 'Condições de Pagamento',
            },
        ),
    ]
