# Generated by Django 3.1.2 on 2021-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.CharField(max_length=100, unique=True, verbose_name='Quantidade'),
        ),
    ]
