# Generated by Django 3.1.2 on 2021-02-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Quantidade'),
        ),
    ]
