# Generated by Django 3.1.2 on 2021-01-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='UF',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
