# Generated by Django 3.1.2 on 2021-10-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='key',
            field=models.CharField(blank=True, max_length=50, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='senha',
            field=models.CharField(blank=True, max_length=200, verbose_name='Senha'),
        ),
    ]
