# Generated by Django 3.1.2 on 2021-01-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20210106_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='UF',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='senha',
            field=models.CharField(blank=True, max_length=14, verbose_name='Senha'),
        ),
    ]
