# Generated by Django 3.1.2 on 2021-10-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_auto_20211025_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='data_de_admissao',
            field=models.DateField(verbose_name='Data de admissão'),
        ),
    ]
