# Generated by Django 3.1.2 on 2021-05-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('qualidades', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precificacao',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='valores_fornecedor', to='fornecedores.fornecedores'),
        ),
        migrations.AlterField(
            model_name='precificacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto', to='produtos.produtos'),
        ),
        migrations.AlterField(
            model_name='precificacao',
            name='qualidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='valores_qualidade', to='qualidades.qualidades'),
        ),
    ]
