# Generated by Django 3.1.2 on 2021-05-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='cod_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Produtos', to='produtos.produtos'),
        ),
    ]
