# Generated by Django 3.1.2 on 2021-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='entrada_saida',
            field=models.CharField(max_length=1, verbose_name='E/S'),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
