# Generated by Django 3.1.2 on 2021-08-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimentacoes', '0001_initial'),
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoes',
            name='cod_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Produto', to='precificacao.precificacao'),
        ),
    ]
