# Generated by Django 3.1.2 on 2021-01-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesDeMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100, verbose_name='descricao')),
                ('sigla', models.CharField(max_length=6, verbose_name='sigla')),
            ],
            options={
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
    ]
